CREATE DATABASE IF NOT EXISTS guestbook;

USE guestbook;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    message VARCHAR(255) NOT NULL
);